SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml

# training data
DATASETS: [PigTrack, PigDetect, PigDetect]
DATASET_SPLITS: [train, dev, test]
DATASET_SEQMAP_NAMES: [~, ~, ~]
# DATASET_WEIGHTS: [2, 2, 1]

# Different pretrain weights:
DETR_PRETRAIN: ~
PRETRAIN: ./pretrained/full_model/r50_deformable_detr_motip_dancetrack_trainval_joint_ch.pth

# # Data augmentation setting for static images:
# AUG_RANDOM_SHIFT_MAX_RATIO: 0.05
# # Larger image size:
# AUG_RESIZE_SCALES: [608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992]
# AUG_MAX_SIZE: 1536
# AUG_RANDOM_RESIZE: [800, 1000, 1200]
# AUG_RANDOM_CROP_MIN: 800
# AUG_RANDOM_CROP_MAX: 1200
# INFERENCE_MAX_SIZE: 1536

# # Different training strategy:
# EPOCHS: 12
# SCHEDULER_MILESTONES: [10, ]

# # To avoid CUDA OOM:
# AUTO_MEMORY_OPTIMIZED_DETR_CRITERION: True
# DETR_CHECKPOINT_FRAMES: 2

# wandb
EXP_NAME: r50_deformable_detr_motip_pigtrack_joint_pigdetect

# Inference:
INFERENCE_DATASET: PigTrack
INFERENCE_SPLIT: val
INFERENCE_MAX_SIZE: 1333
# # Thresholds (not changed from base config):
# ID_THRESH: 0.2
# DET_THRESH: 0.3 # only consider detections whose confidence exceeds this threshold
# NEWBORN_THRESH: 0.6 # only consider detections whose confidence exceeds this threshold for newborn objects (stricter than DET_THRESH)
# AREA_THRESH: 100 # only consider detections whose area exceeds this threshold