SUPER_CONFIG_PATH: ./configs/pretrain_r50_deformable_detr_dancetrack.yaml

# Joint CrowdHuman:
DATASETS: [DanceTrack, CrowdHuman, CrowdHuman]
DATASET_SPLITS: [train, train, val]
DATASET_WEIGHTS: [1, 3, 3]

EPOCHS: 60
SCHEDULER_MILESTONES: [45, ]

SAVE_CHECKPOINT_PER_EPOCH: 5