SUPER_CONFIG_PATH: ./configs/base.yaml
MODE: ~ # "train" or "inference" or "video_inference"
EXP_NAME: ~

# training data
DATA_ROOT: ../data/datasets
DATASETS: [DanceTrack, crowdhuman, crowdhuman]
DATASET_SPLITS: [train, train, val]
DATASET_SEQMAP_NAMES: [~, ~, ~]
DATASET_TYPES: ['track', 'det', 'det']
# DATASET_WEIGHTS: [2, 2, 1]

# pretrained weights:
DETR_PRETRAIN: ../data/pretrained/motip/detr/r50_deformable_detr_coco_dancetrack_joint_ch.pth
PRETRAIN: ~ # complete pretrained model (as opposed to DETR_PRETRAIN)

# Training:
TRAIN_STAGE: joint
EPOCHS: 12
SCHEDULER_MILESTONES: [10, ]

# Inference:
INFERENCE_DATASET: DanceTrack
INFERENCE_SPLIT: val
INFERENCE_ONLY_DETR: False
INFERENCE_MAX_SIZE: 1536 # width of image after resizing; maybe only resized if image width originally is bigger
INFERENCE_ENSEMBLE: 0
VISUALIZE_INFERENCE: False
ID_THRESH: 0.2
DET_THRESH: 0.3 # only consider detections whose confidence exceeds this threshold
NEWBORN_THRESH: 0.6 # only consider detections whose confidence exceeds this threshold for newborn objects (stricter than DET_THRESH)
AREA_THRESH: 100 # only consider detections whose area exceeds this threshold

# Additional video inference settings:
INFERENCE_MODEL: ~
VIDEO_DIR: ~ # provide in case of video inference

# Data augmentation setting for static images:
AUG_RANDOM_SHIFT_MAX_RATIO: 0.05
# Larger image size:
AUG_RESIZE_SCALES: [608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992]
AUG_MAX_SIZE: 1536
AUG_RANDOM_RESIZE: [800, 1000, 1200]
AUG_RANDOM_CROP_MIN: 800
AUG_RANDOM_CROP_MAX: 1200

# To avoid CUDA OOM:
AUTO_MEMORY_OPTIMIZED_DETR_CRITERION: True
DETR_CHECKPOINT_FRAMES: 2
