SUPER_CONFIG_PATH: ./configs/dt_train_ch_all.yaml
MODE: ~ # "train" or "inference" or "video_inference"
EXP_NAME: ~

# training data
DATA_ROOT: ../data/datasets
DATASETS: [DanceTrack, DanceTrack, crowdhuman, crowdhuman]
DATASET_SPLITS: [train, val, train, val]
DATASET_SEQMAP_NAMES: [~, ~, ~, ~]
DATASET_TYPES: ['track', 'track', 'det', 'det']
# DATASET_WEIGHTS: [2, 2, 1]

# pretrained weights:
DETR_PRETRAIN: ../data/pretrained/motip/detr/r50_deformable_detr_coco_dancetrack_trainval_joint_ch.pth
PRETRAIN: ~ # complete pretrained model (as opposed to DETR_PRETRAIN)

# Training:
TRAIN_STAGE: joint
EPOCHS: 14
SCHEDULER_MILESTONES: [10, 12, ]

# Inference:
INFERENCE_DATASET: DanceTrack
INFERENCE_SPLIT: val
INFERENCE_ONLY_DETR: False
INFERENCE_MAX_SIZE: 1333 # width of image after resizing; maybe only resized if image width originally is bigger
INFERENCE_ENSEMBLE: 0
VISUALIZE_INFERENCE: False
ID_THRESH: 0.2
DET_THRESH: 0.3 # only consider detections whose confidence exceeds this threshold
NEWBORN_THRESH: 0.6 # only consider detections whose confidence exceeds this threshold for newborn objects (stricter than DET_THRESH)
AREA_THRESH: 100 # only consider detections whose area exceeds this threshold

# Additional video inference settings:
INFERENCE_MODEL: ~
VIDEO_DIR: ~ # provide in case of video inference
