SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml

# training data
DATASETS: [PigTrack, PigDetect, PigDetect]
DATASET_SPLITS: [train, train, val]
DATASET_WEIGHTS: [1, 1, 1] 


SAMPLE_LENGTHS: [1]       # Only sampling one frame for detection

DETR_PRETRAIN: ./pretrains/r50_deformable_detr_coco.pth   # Pretrain from COCO checkpoint
DETR_NUM_TRAIN_FRAMES: 100                                # >> BS

# Train Setting:
TRAIN_STAGE: only_detr
EPOCHS: 16
LR: 2.0e-4
LR_WARMUP_EPOCHS: 0
SCHEDULER_MILESTONES: [12, ]
SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 4
ACCUMULATE_STEPS: 1

# Eval:
INFERENCE_ONLY_DETR: True
SAVE_CHECKPOINT_PER_EPOCH: 4