SUPER_CONFIG_PATH: ./configs/base.yaml
MODE: ~ # "train" or "inference" or "video_inference"
EXP_NAME: ~

# training data
DATA_ROOT: ../data/datasets
DATASETS: [PigTrack, PigDetect, PigDetect]
DATASET_SPLITS: [train, dev, test]
DATASET_SEQMAP_NAMES: [~, ~, ~]
DATASET_TYPES: ['track', 'det', 'det']
# DATASET_WEIGHTS: [2, 2, 1]

# pretrained weights:
DETR_PRETRAIN: ../data/pretrained/motip/detr/r50_deformable_detr_coco.pth # Pretrain from COCO checkpoint
PRETRAIN: ~

# Training:
TRAIN_STAGE: only_detr
EPOCHS: 16
LR: 2.0e-4
LR_WARMUP_EPOCHS: 0
SCHEDULER_MILESTONES: [12, ]
SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 4
ACCUMULATE_STEPS: 1

# Inference:
INFERENCE_DATASET: PigTrack
INFERENCE_SPLIT: val
INFERENCE_ONLY_DETR: True
INFERENCE_MAX_SIZE: 1333 # width of image after resizing; maybe only resized if image width originally is bigger
INFERENCE_ENSEMBLE: 0
VISUALIZE_INFERENCE: False
ID_THRESH: 0.2
DET_THRESH: 0.3 # only consider detections whose confidence exceeds this threshold
NEWBORN_THRESH: 0.6 # only consider detections whose confidence exceeds this threshold for newborn objects (stricter than DET_THRESH)
AREA_THRESH: 100 # only consider detections whose area exceeds this threshold

# Additional video inference settings:
INFERENCE_MODEL: ~
VIDEO_DIR: ~ # provide in case of video inference

# detection specific settings
SAMPLE_LENGTHS: [1]       # Only sampling one frame for detection
DETR_NUM_TRAIN_FRAMES: 100                                # >> BS

