SUPER_CONFIG_PATH: ./configs/r50_ddetr_dt_train_joint_ch.yaml

# Joint training with crowdhuman:
DATASETS: [DanceTrack, DanceTrack, crowdhuman, crowdhuman]
DATASET_SPLITS: [train, val, train, val]
DATASET_SEQMAP_NAMES: [~, ~, ~, ~]
DATASET_TYPES: ['track', 'track', 'det', 'det']

# Different pretrain weights:
DETR_PRETRAIN: ./datasets/pretrained/detr/r50_deformable_detr_coco_dancetrack_trainval_joint_ch.pth

# Different training strategy:
EPOCHS: 14
SCHEDULER_MILESTONES: [10, 12, ]
